name: Build and Release

on:
  workflow_dispatch:  # Permite ejecutar el workflow manualmente desde GitHub
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'  # Usamos la versión de Python que más te convenga

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate .exe with PyInstaller
      run: |
        pyinstaller --onefile --windowed main.py

    - name: Upload .exe as artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-app
        path: dist/tu_codigo.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create a release
      id: release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/tu_codigo.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
