name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Esto hace que el flujo de trabajo se active cuando se cree un tag que empiece con 'v', por ejemplo v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Usamos la versión de Python que más te convenga

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate .exe with PyInstaller
      run: |
        pyinstaller --onefile --windowed main.py

    - name: Upload .exe as artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-app
        path: dist/tu_codigo.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create a release
      id: release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/tu_codigo.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
